FROM alpine:latest
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache gcc git python3 python3-dev && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

RUN mkdir /data \
    # Clone the repo and install requirements
    && cd / && git clone 'https://github.com/andydeangelis/ComicDownloader.git' \
    # Switching to dev branch here
    && cd /ComicDownloader && git switch comicdownloader-dev \
    && pip3 install -r /ComicDownloader/requirements.txt \
    # Create empty directory to mount comic library
    && mkdir /comics \
    # Clone and build comictagger
    && cd / && git clone 'https://github.com/comictagger/comictagger.git' \
    && cd /comictagger && git switch develop \
    && pip3 install -r /comictagger/requirements_dev.txt \
    && cd /comictagger && python setup.py install

ENTRYPOINT ["python3", "/ComicDownloader/__main__.py"]